language: cpp
matrix:
  include:
    - os: linux
      env: LIBTORRENT_BRANCH=RC_1_2 TOOLCHAIN="CXX=g++-8 CC=gcc-8 CPP=cpp-8"
    - os: linux
      env: LIBTORRENT_BRANCH=RC_1_1 TOOLCHAIN="CXX=g++-8 CC=gcc-8 CPP=cpp-8"
    - os: osx
      env: LIBTORRENT_BRANCH=RC_1_2
    - os: osx
      env: LIBTORRENT_BRANCH=RC_1_1
env:
  global:
    - MAKEFLAGS=-j2
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
    - LD_LIBRARY_PATH=/tmp/lib
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - libfuse-dev
      - libcurl4-openssl-dev
      - g++-8
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install Caskroom/cask/osxfuse;
      brew install curl;
    fi
install:
  - env $TOOLCHAIN CXXFLAGS="-fpermissive -w -std=c++11" ./scripts/build-libtorrent $LIBTORRENT_BRANCH /tmp
before_script:
  - autoreconf -i
script:
  - env $TOOLCHAIN ./configure && make && make test
