language: cpp
matrix:
  include:
    - os: linux
      env: LIBTORRENT_BRANCH=master TOOLCHAIN="CXX=g++-7 CC=gcc-7 CPP=cpp-7"
    - os: linux
      env: LIBTORRENT_BRANCH=RC_1_1 TOOLCHAIN="CXX=g++-7 CC=gcc-7 CPP=cpp-7"
    - os: linux
      env: LIBTORRENT_BRANCH=RC_1_0 TOOLCHAIN="CXX=g++-7 CC=gcc-7 CPP=cpp-7"
    - os: osx
      env: LIBTORRENT_BRANCH=master
    - os: osx
      env: LIBTORRENT_BRANCH=RC_1_1
    - os: osx
      env: LIBTORRENT_BRANCH=RC_1_0
  allow_failures:
    - os: linux
      env: LIBTORRENT_BRANCH=master TOOLCHAIN="CXX=g++-7 CC=gcc-7 CPP=cpp-7"
    - os: osx
      env: LIBTORRENT_BRANCH=master
env:
  global:
    - MAKEFLAGS=-j2
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
    - LD_LIBRARY_PATH=/tmp/lib
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - libboost1.55-tools-dev
      - libfuse-dev
      - libcurl4-openssl-dev
      - g++-7
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install Caskroom/cask/osxfuse;
      brew install curl;
    fi
install:
  - env $TOOLCHAIN CXXFLAGS="-fpermissive -w -std=c++11" ./scripts/build-libtorrent $LIBTORRENT_BRANCH /tmp
before_script:
  - autoreconf -i
script:
  - env $TOOLCHAIN ./configure && make && make test
