language: cpp
matrix:
  include:
    - os: linux
      env: LIBTORRENT_BRANCH=master BUILDENV="CXX=g++-7 CC=gcc-7 CPP=cpp-7 CXXFLAGS=-fpermissive"
    - os: linux
      env: LIBTORRENT_BRANCH=RC_1_1 BUILDENV="CXX=g++-7 CC=gcc-7 CPP=cpp-7 CXXFLAGS=-fpermissive"
    - os: linux
      env: LIBTORRENT_BRANCH=RC_1_0 BUILDENV="CXX=g++-7 CC=gcc-7 CPP=cpp-7 CXXFLAGS=-fpermissive"
    - os: osx
      env: LIBTORRENT_BRANCH=master BUILDENV="CXXFLAGS=-std=c++11"
    - os: osx
      env: LIBTORRENT_BRANCH=RC_1_1 BUILDENV="CXXFLAGS=-std=c++11"
    - os: osx
      env: LIBTORRENT_BRANCH=RC_1_0 BUILDENV="CXXFLAGS=-std=c++11"
env:
  global:
    - MAKEFLAGS=-j2
    - PKG_CONFIG_PATH=/tmp/lib/pkgconfig
    - LD_LIBRARY_PATH=/tmp/lib
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - libboost1.55-tools-dev
      - libfuse-dev
      - libcurl4-openssl-dev
      - g++-7
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install Caskroom/cask/osxfuse;
      brew install curl;
    fi
install:
  - env $BUILDENV ./scripts/build-libtorrent $LIBTORRENT_BRANCH /tmp
before_script:
  - autoreconf -i
script:
  - env $BUILDENV ./configure && make && make test
